snu_0 : 1e-5 # 動粘性係数
hmin : 0.001 # 最小水深(m)
cw: 0.01 # 側壁摩擦係数
ep_alpha: 1. # 渦動粘性係数の係数
nx: 50 # x方向のセル数(ノードは0からnxまでnx+1個となる)
ny: 20 # y方向のセル数(ノードは0からnyまでny+1個となる)
chl: 5 # 水路長(m)
chb: 1 # 水路幅(m)
slope: 0.001 # 水路勾配
xsize: 20 # 計算結果をプロットする図の横スケール
qp: 0.05 # 流量(m^3/s)
snm: 0.02 # マニング粗度
g: 9.8 # 重力加速度(m/s^2)

j_west: 0 # 上流条件(0:開放, 1:閉鎖)
j_east: 0 # 下流条件(0:開放, 1:閉鎖)
j_hdown: 1 # 下流端水位条件(0:自由流出, 1:等流水深, 2:固定水位を与える)
# h_down : 10. # j_hdown=2 の時の固定水位(m)

alh: 0.6 # 水位収束計算のReluxsation係数
lmax: 10 # 各タイムステップでの水位収束計算最大回数

etime: 100 # 計算終了時間(sec)
tuk: 0.1 # 計算結果アウトプット間隔(sec)
dt: 0.02 # 計算タイムステップ(sec)

